############# English navigation ##############

[[main]]
weight = 1
name = "Who We Are"
hasChildren = true

  [[main]]
  parent = "Who We Are"
  name = "Our Vision"
  url = "who-we-are/#our-vision"
  weight = 1

  [[main]]
  parent = "Who We Are"
  name = "Our Team"
  url = "who-we-are/#our-team"
  weight = 2
  
[[main]]
weight = 2
name = "What We Do"
hasChildren = true

  [[main]]
  parent = "What We Do"
  name = "Hackathon"
  url = "what-we-do/"
  weight = 1

  [[main]]
  parent = "What We Do"
  name = "Capture The Flag"
  url = "what-we-do/"
  weight = 2


[[main]]
weight = 3
name = "Our Projects"
url = "our-projects/"

[[main]]
weight = 4
name = "eservices"
url = "eservices"

[[main]]
weight = 5
name = "Learn"
url = "learn/"

[[main]]
weight = 6
name = "Connect Now"
url = "connect-now/"

[[footer]]
name = "Privacy Statement"
url = "privacy-statement"
weight = 1

[[footer]]
name = "Terms of Use"
url = "terms-of-use"
weight = 2