#################### default parameters ################################

favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "300px"
logo_text = "Isolated Command"
navbar_fixed = false
description = "Isolated Command | No Boundaries, No Limits"
author = "conanzhangtech"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
address_descriptors = false
email = "hello@isolatedcommand.com"
copyright = "Isolated Command 2026"
custom_script= ""
google_tag_manager = ""
recaptcha_site_key = ""

[contact.form]
enable = false
use_netlify = false
use_recaptcha = true
action = "#"
success_image = ""

[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

[navigation_button]
enable = true
label = "get a quote"
link = "contact"


[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

[baidu]
enable = false
analytics_id = "" # Your ID

[plausible]
enable = false
domain = "" # yourdomain.com

[counter]
enable = false
id = "" # your site's counter.dev ID (`data-id` attribute value)
utc_offset = 0 # UTC time offset (`data-utcoffset` attribute value)

[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code

[gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
# available widget : categories,tags,recent-post


############################# social site ########################=
[[social]]
title = "instagram"
icon = "fa-brands fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://go.isolatedcommand.com/instagram"

[[social]]
title = "github"
icon = "fa-brands fa-square-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://go.isolatedcommand.com/github"

[[social]]
title = "linkedin"
icon = "fa-brands fa-square-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://go.isolatedcommand.com/linkedin"

[[social]]
title = "linkedin"
icon = "fa-brands fa-dev" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://go.isolatedcommand.com/linkedin"
