#project name
name = 'isolatedcommand-com'
# ensures that this will be compatible for this specific version of Cloudflare Workers
compatibility_date = '2025-07-31'
# disables *.workers.dev URL
workers_dev = false
# disables preview URLs
preview_urls = false

[assets]
# directory of static files
directory = './public'
# tells the worker that you have a custom 404 page when a requested
# asset is not found, and should be found in the directory set in the above line.
not_found_handling = '404'