######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#3272c8"
body_color = "#fff"
text_color = "white"
text_red = "red"
text_blue = "#3272c8"
text_dark = "white"
text_light = "white"
border_color = "white"
black = "#000000"
white = "#fff"
light = "white"

# font variables
# base font size for full website, 
font_size = "15px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Roboto+Slab:wght@300;400"
font_primary_type = "monospace" # [serif/sans-serif]
font_secondary = "Roboto+Slab:wght@300;400"
font_secondary_type = "monospace" # [serif/sans-serif]
font_icon = "Font Awesome 5 Free" # https://fontawesome.com/v5.15/icons/


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/font-awesome/fontawesome.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"